---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "build-pipeline.labels" . | nindent 4 }}
spec:
  serviceAccountName: pipeline
  triggers:
    - name: main-branch-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: body.ref == 'refs/heads/main'
      bindings:
        - ref: {{ .Chart.Name }}-main
      template:
        ref: {{ .Chart.Name }}-main

    - name: pull-requests-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "eventTypes"
              value: ["pull_request"]
        - name: "only when PRs are opened"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: {{ .Chart.Name }}
      template:
        ref: {{ .Chart.Name }}

