apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-shared-data
  labels:
    type: pipeline
    {{- include "build-pipeline.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
