kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
  labels:
    {{- include "build-pipeline.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
secrets:
  - name: dockerconfig
  - name: docker-registry-config