---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ .Chart.Name }}
  labels:
    type: pipeline
    {{- include "build-pipeline.labels" . | nindent 4 }}
spec:
  params:
    - name: git-revision
      description: The git revision
    - name: git-repo-url
      description: The application's repo url 
    - name: git-repo-name
      description: repository name
    - name: git-repo-full-name
      description: repository full name
    - name: head-sha
      description: reference of the image that will get created
    - name: pr-number
      description: pull request number
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.git-repo-name)-
        labels:
          backstage.io/kubernetes-id: $(tt.params.git-repo-name)
      spec:
        params:
          - name: source-repo
            value: $(tt.params.git-repo-url)
          - name: source-branch
            value: $(tt.params.git-revision)
          - name: app-name
            value: $(tt.params.git-repo-name)
          - name: registry
            value: quay.io/rhn_gps_vpogu
          - name: tenant-cicd-repo-branch-name
            value: $(tt.params.pr-number)-$(tt.params.git-repo-name)
          - name: image-tag
            value: $(tt.params.head-sha)
          - name: helm-deploy-values
            value: {{.Values.applicationRepo.clusterDeployment}}/{{.Values.applicationRepo.teamName}}/$(tt.params.git-repo-name)/deploy/dev-values.yaml
        pipelineRef:
          name: {{ .Chart.Name }}
        serviceAccountName: pipeline
        workspaces:
          - name: source-shared-data
            persistentVolumeClaim:
              claimName: source-shared-data
          - name: maven-settings 
            emptyDir: {} 
          - name: output-shared-data
            persistentVolumeClaim:
              claimName: output-shared-data
          - name: docker-config
            secret:
              secretName: pipeline-build-secret
          - name: git-config
            secret:
              secretName: pipeline-build-secret